version: "3.9"

services:
   elastic:
      image: elasticsearch:7.14.0
      labels:
         author: "Houston Santos - houston_santos@hotmail.com" 
      container_name: elastic
      environment:
         - http.host=0.0.0.0
         - node.name=elastic
         - discovery.type=single-node
         - xpack.security.enabled=true
         - ELASTIC_USER=$ELASTIC_USER
         - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      ulimits: 
         memlock:
            soft: -1
            hard: -1
         #nofile:
         #   soft: 65536
         #   hard: 65536
      #cap_add: 
      #   - IPC_LOCK
      healthcheck:
         test: curl -f -i -u elastic:elastic http://localhost:9200
      restart: on-failure
      #volumes: 
      #  - data01:/usr/share/elasticsearch/data
      ports: 
         - 9200:9200
      networks: 
         - elastic
    
   kibana: 
      image: kibana:7.14.0
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: kibana
      depends_on: 
         - elastic
      environment:
         SERVER_NAME: kibana
         SERVER_HOST: 0.0.0.0 
         ELASTICSEARCH_URL: http://elastic:9200
         ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
         XPACK_SECURITY_ENABLED: true
         ELASTICSEARCH_USERNAME: ${ELASTIC_USER}
         ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
      healthcheck:
         test: curl -f -i http://localhost:5601/login
      restart: on-failure
      #volumes: 
      #    - data02:/usr/share/elasticsearch/data
      ports: 
         - 5601:5601
      networks: 
         - elastic
    
   logstash:
      image: logstash:7.14.0
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: logstash
      depends_on: 
         - elastic
      environment: 
         XPACK.MONITORING.ELASTICSEARCH.HOSTS: http://elastic:9200
      restart: on-failure
      volumes:
         - /Users/houston/Repositorios/Docker/ElasticStack/logstash:/mnt
         # - data03:/usr/share/elasticsearch/data
      ports: 
         - 5044:5044
      networks: 
         - elastic

# volumes: 
   # data01:
   # data02:
   # data03:

networks: 
   elastic:
      name: elastic