version: "3.9"

services:
   #postgres:
   #   build: 
   #      context: .
   #      dockerfile: postgres/dockerfile.postgres
   #   # image: postgres:13.4
   #   labels: 
   #      author: "Houston Santos - houston_santos@hotmail.com"
   #   container_name: postgres
   #   environment:
   #      POSTGRES_PASSWORD: postgres
   #      # docker POSTGRES_INITDB_ARGS: "--encoding=WIN1252 --locale=C --username=postgres"
   #   restart: always
   #   ports:
   #      - 5432:5432
   #   networks:
   #      - elastic

   elastic:
      image: elasticsearch:7.14.0
      labels:
         author: "Houston Santos - houston_santos@hotmail.com" 
      container_name: elastic
      environment:
         - http.host=0.0.0.0
         - node.name=elastic
         - discovery.type=single-node
      ulimits: 
         memlock:
            soft: -1
            hard: -1
         #nofile:
         #   soft: 65536
         #   hard: 65536
      #cap_add: 
      #   - IPC_LOCK
      restart: on-failure
      #volumes: 
      #  - data01:/usr/share/elasticsearch/data
      ports: 
         - 9200:9200
      networks: 
         - elastic
    
   kibana: 
      image: kibana:7.14.0
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: kibana
      depends_on: 
         - elastic
      environment:
         SERVER_NAME: kibana
         SERVER_HOST: 0.0.0.0 
         ELASTICSEARCH_URL: http://elastic:9200
         ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
      restart: on-failure
      #volumes: 
      #    - data02:/usr/share/elasticsearch/data
      ports: 
         - 5601:5601
      networks: 
         - elastic
    
   logstash:
      image: logstash:7.14.0
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: logstash
      depends_on: 
         - elastic
      environment: 
         XPACK.MONITORING.ELASTICSEARCH.HOSTS: http://elastic:9200
      restart: on-failure
      volumes:
         # - C:\Users\houston.santos\Repo\ElasticStack\logstash:/mnt
         - /Users/houston/Repositorios/Docker/ElasticStack/logstash:/mnt
         # - data03:/usr/share/elasticsearch/data
      ports: 
         - 5044:5044
      networks: 
         - elastic

# volumes: 
   # data01:
   # data02:
   # data03:

networks: 
   elastic:
      name: elastic