version: "3.9"

services: 
    elastic:
        image: elasticsearch:7.13.2
        container_name: elastic
        environment: 
            - discovery.type=single-node
            - node.name=elastic
        ulimits: 
            memlock:
                soft: -1
                hard: -1
        volumes: 
            - data01:/usr/share/elasticsearch/data
        ports: 
            - "9200:9200"
        networks: 
            - elastic
    
    kibana: 
        image: kibana:7.13.2
        container_name: kibana
        environment: 
            - server.name=kibana
            - server.host=0.0.0.0
            - elasticsearch.url=http//elastic:9200
            - elasticsearch.hosts=http//elastic:9200
        volumes: 
            - data02:/usr/share/elasticsearch/data
        ports: 
            - "5601:5601"
        networks: 
            - elastic
    
    logstash:
        image: logstash:7.13.2
        container_name: logstash
        environment: 
            - XPACK.MONITORING.ELASTICSEARCH.HOSTS=http://elastic:9200
        volumes: 
            - data03:/usr/share/elasticsearch/data
        ports: 
            - "5044:5044"
        networks: 
            - elastic

volumes: 
    data01:
    data02:
    data03:

networks: 
    elastic:
        name: elastic