version: "3.9"

services:    
   #filebeat:
   #   image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
   #   labels: 
   #      author: "Houston Santos - houston_santos@hotmail.com"
   #   container_name: filebeat
   #   restart: on-failure
   #   environment:
   #     - TZ=${TIMEZONE}
   #   user: root
   #   command: filebeat -e -strict.perms=false
   #   healthcheck:
   #      test: filebeat -strict.perms=false test config
   #   restart: on-failure
   #   volumes:
   #      - ./beats/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
   #      - /var/lib/docker/containers:/var/lib/docker/containers:ro
   #      - /var/run/docker.sock:/var/run/docker.sock:ro
   #   ports: 
   #      - 2055:2055/udp
   #   networks:
   #      - elastic

   metricbeat:
      image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: metricbeat
      #privileged: true
      restart: on-failure
      environment:
         - TZ=${TIMEZONE}
      user: root
      command: metricbeat -e -strict.perms=false
      healthcheck:
         test: metricbeat -strict.perms=false test config
      volumes:
         - ./beats/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
         - /var/lib/docker/containers:/var/lib/docker/containers:ro
         - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
         - elastic
         - databases

#volumes: 
   # filebeat:

networks: 
   elastic:
      external: true
   databases:
      external: true