version: "3.9"

services:
   elastic:
      image: elasticsearch:7.14.1
      labels:
         author: "Houston Santos - houston_santos@hotmail.com" 
      container_name: elastic
      environment:
         - http.host=0.0.0.0
         - node.name=elastic
         - discovery.type=single-node
         - xpack.security.enabled=true
         #- xpack.monitoring.collection.enabled=true
         #- xpack.security.http.ssl.enabled=true
         #- xpack.security.transport.ssl.enabled=true
         - ELASTIC_USER=$ELASTIC_USER
         - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      #ulimits: 
      #   memlock:
      #      soft: -1
      #      hard: -1
         #nofile:
         #   soft: 65536
         #   hard: 65536
      #cap_add: 
      #   - IPC_LOCK
      healthcheck:
         test: curl -f -i -u elastic:elastic http://localhost:9200
      restart: on-failure
      #volumes: 
      #  - elastic:/usr/share/elasticsearch/data
      ports: 
         - 9200:9200
      networks: 
         - elastic
    
   kibana: 
      image: kibana:7.14.1
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: kibana
      depends_on: 
         - elastic
      environment:
         SERVER_NAME: kibana
         SERVER_HOST: 0.0.0.0
         #SERVER_SSL_ENABLED: true 
         #XPACK_SECURITY_ENABLED: true
         #MONITORING_ENABLED: true
         ELASTICSEARCH_URL: http://elastic:9200
         ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
         ELASTICSEARCH_USERNAME: ${ELASTIC_USER}
         ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
      healthcheck:
         test: curl -f -i http://localhost:5601/login
      restart: on-failure
      #volumes: 
      #    - kibana:/usr/share/kibana/data
      ports: 
         - 5601:5601
      networks: 
         - elastic
    
   logstash:
      image: logstash:7.14.1
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: logstash
      depends_on: 
         - elastic
      #environment:
         #XPACK.MONITORING.ELASTICSEARCH.USERNAME: elastic
         #XPACK.MONITORING.ELASTICSEARCH.PASSWORD: elastic
         #XPACK.MONITORING.ELASTICSEARCH.HOSTS: http://elastic:9200
      restart: on-failure
      volumes:
         - /Users/houston/Repositorios/Docker/ElasticStack/logstash:/mnt
         # - logstash:/usr/share/logstash/data
      ports: 
         - 5044:5044
      networks: 
         - elastic
         - databases

   metricbeat:
      image: docker.elastic.co/beats/metricbeat:7.14.1-amd64
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: metricbeat
      depends_on: 
         - logstash
         - kibana
      environment: 
         - setup.kibana.host=kibana:5601
         - output.elasticsearch.hosts=["elastic:9200"]
      restart: on-failure
      networks: 
         - elastic

# volumes: 
   # elastic:
   # kibana:
   # logstash:

networks: 
   elastic:
      name: elastic
   databases:
      external: true