version: "3.9"

services:
  eslasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: eslasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #volumes:
    #  - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana
    environment:
      #ELASTICSEARCH_URL: http://localhost:9200
      ELASTICSEARCH_HOSTS: http://localhost:9200
    ports:
      - 5601:5601
    networks:
      - elastic
  
  #volumes:
  #  data01:
  #    driver: local
  #  data02:
  #    driver: local

networks: 
  elastic:
    name: elastic