version: "3.9"

services:
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1-amd64
      labels:
         author: "Houston Santos - houston_santos@hotmail.com" 
      container_name: elasticsearch
      environment:
         - http.host=0.0.0.0
         - node.name=elastic
         - discovery.type=single-node
         - xpack.security.enabled=true
         - xpack.monitoring.collection.enabled=true
         #- xpack.security.http.ssl.enabled=true
         #- xpack.security.transport.ssl.enabled=true
         - ELASTIC_USER=${ELASTIC_USER}
         - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      ulimits: 
         memlock:
            soft: -1
            hard: -1
         #nofile:
         #   soft: 65536
         #   hard: 65536
      #cap_add: 
      #   - IPC_LOCK
      healthcheck:
         test: curl -f -i -u ${ELASTIC_USER}:${ELASTIC_PASSWORD} http://localhost:9200
      restart: on-failure
      volumes: 
         - elasticsearch:/usr/share/elasticsearch/data
      ports: 
         - 9200:9200
      networks: 
         - elastic
    
   kibana: 
      image: docker.elastic.co/kibana/kibana:7.15.1-amd64
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: kibana
      depends_on: 
         - elastic
      environment:
         SERVER_NAME: kibana
         SERVER_HOST: 0.0.0.0
         #SERVER_SSL_ENABLED: true 
         #XPACK_SECURITY_ENABLED: true
         #MONITORING_ENABLED: true
         ELASTICSEARCH_URL: http://elasticsearch:9200
         ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
         ELASTICSEARCH_USERNAME: ${ELASTIC_USER}
         ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
      healthcheck:
         test: curl -f -i http://localhost:5601/login
      restart: on-failure
      volumes: 
         - kibana:/usr/share/kibana/data
      ports: 
         - 5601:5601
      networks: 
         - elastic
    
   logstash:
      image: docker.elastic.co/logstash/logstash:7.15.1-amd64
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: logstash
      depends_on: 
         - elastic
      environment:
         XPACK.MONITORING.ELASTICSEARCH.USERNAME: ${ELASTIC_USER}
         XPACK.MONITORING.ELASTICSEARCH.PASSWORD: ${ELASTIC_PASSWORD}
         XPACK.MONITORING.ELASTICSEARCH.HOSTS: http://elasticsearch:9200
      restart: on-failure
      volumes:
         - ./logstash/lib:/mnt
         - ./logstash/pipeline:/usr/share/logstash/pipeline
         - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
         #- ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      ports:
         - 5044:5044
      networks: 
         - elastic
         - databases

volumes: 
   elasticsearch:
   kibana:
   #logstash:

networks: 
   elastic:
      name: elastic
   databases:
      external: true