# Imagem Docker
FROM postgres:13.4

# Instalando depedências e driver ODBC
# nano iputils-ping net-tools procps locate apt-file
RUN apt-get update && apt-get install -y odbc-postgresql unixodbc && apt-get clean

# Atualizando base locate
# RUN updatedb && apt-file update

# Copiando script de criação de database 
COPY postgres/db_postgres.sh /docker-entrypoint-initdb.d

# Expondo porta de conexão Postgres
EXPOSE 5432